### ISSUE TITLE
[feat] New Comparators

### ISSUE THREAD

**Issue by BorysShulyak** [mattmilburn/strapi-plugin-do-not-delete#13]
@mattmilburn Here is the list of comparators that could be implemented. What do you think about this list and the comparators naming? Could I take this task in progress?
- `lessThan`
- `lessThanOrEqual`
- `greaterThan`
- `greaterThanOrEqual`
- `between`

**Comment by BorysShulyak** [comment]
@mattmilburn after completing this task, I would like to write and publish an article about this plugin on [my blog](https://dev.to/borysshulyak). In this article, I would describe the use cases, configuration instructions, usage examples, a list of APIs, invite people to contribute to this project, and also indicate you as the creator and maintainer. What do you think about it ? Don't you mind?

**Comment by mattmilburn** [comment]
@BorysShulyak That would be great to add these new comparators! What do you think about using `lt`, `gt`, `lte`, and `gte` for the less/greater comparator keys?

**Comment by mattmilburn** [comment]
@BorysShulyak Absolutely, that would be great! ❤️  Let me know when you post it 🙂

**Comment by mattmilburn** [comment]
> @mattmilburn after completing this task, I would like to write and publish an article about this plugin on [my blog](https://dev.to/borysshulyak). In this article, I would describe the use cases, configuration instructions, usage examples, a list of APIs, invite people to contribute to this project, and also indicate you as the creator and maintainer. What do you think about it ? Don't you mind?

@BorysShulyak Absolutely, that would be great! ❤️  Let me know when you post it 🙂

**Comment by mattmilburn** [comment]
After these new comparators are implemented, the plugin will be able to release version 1.1.0 👍🏻

**Comment by BorysShulyak** [comment]
https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/15 Ready for the review!
