### ISSUE TITLE
Is there a way to avoid deleting a specific single type?

### ISSUE THREAD

**Issue by Esteban-Pi** [mattmilburn/strapi-plugin-do-not-delete#3]
I want to avoid users to delete a specific single type without any specific extra rule. I've tried something like this in the plugin configuration:

```
'do-not-delete': {
    config: {
      contentTypes: {
        'api::my-single-type.my-single-type': [[]],
      },
    },
  },
```

But it doesn't work. Is there a way to accomplish what I need?
Thanks!

**Comment by mattmilburn** [comment]
Hi @Esteban-Pi Currently there is not a direct way to do it. For now, you could use a regular expression that would always return true. See the example below:

```js
'api::my-single-type.my-single-type': [
  [ 'id', 'matches', '\\d' ],
],
```

This matches any `id` that is a number value which will always return true.

I'll certainly consider a better option for this in future updates 👍🏻
