### ISSUE TITLE
Set up `jest` and cover the existing functionality with tests

### ISSUE THREAD

**Issue by BorysShulyak** [mattmilburn/strapi-plugin-do-not-delete#9]

**Comment by BorysShulyak** [comment]
@mattmilburn Could I take this task in progress?

**Comment by mattmilburn** [comment]
@BorysShulyak Yes please, that would be helpful!

**Comment by BorysShulyak** [comment]
https://github.com/mattmilburn/strapi-plugin-do-not-delete/pull/11
